package queryset

import (
	"bytes"
	"fmt"
	"io"
	"log"
	"os"
	"text/template"

	"github.com/to6ka/go-queryset/parser"
	"github.com/to6ka/go-queryset/queryset/methods"
	"golang.org/x/tools/go/loader"
	"golang.org/x/tools/imports"
)

type Config struct {
	DBImport string
	methods.Config
}

// GenerateQuerySets generates output file with querysets
func GenerateQuerySets(inFilePath, outFilePath string, cfg Config) error {
	pkgInfo, structs, err := parser.GetStructsInFile(inFilePath)
	if err != nil {
		return fmt.Errorf("can't parse file %s to get structs: %s", inFilePath, err)
	}

	var r io.Reader
	r, err = generateQuerySetsForStructs(pkgInfo, structs, cfg)
	if err != nil {
		return fmt.Errorf("can't generate query sets: %s", err)
	}

	if r == nil {
		return fmt.Errorf("no structs to generate query set in %s", inFilePath)
	}

	if err = writeQuerySetsToOutput(r, pkgInfo, outFilePath, cfg); err != nil {
		return fmt.Errorf("can't save query sets to out file %s: %s", outFilePath, err)
	}

	return nil
}

const headerTemplateRaw = `// Code generated by goqueryset, DO NOT EDIT.
package {{ .Package }}

import (
	"fmt"
	"time"

	"{{ .DBImport }}"
)
`

var headerTmpl = template.Must(template.New("header").Parse(headerTemplateRaw))

type headerData struct {
	Package  string
	DBImport string
}

func writeQuerySetsToOutput(r io.Reader, pkgInfo *loader.PackageInfo, outFile string, cfg Config) error {
	var buf bytes.Buffer

	err := headerTmpl.Execute(&buf, headerData{
		Package:  pkgInfo.Pkg.Name(),
		DBImport: cfg.DBImport,
	})
	if err != nil {
		return fmt.Errorf("can't execute template header to buf: %s", err)
	}

	if _, err := io.Copy(&buf, r); err != nil {
		return fmt.Errorf("can't write to buf: %s", err)
	}
	//log.Printf("output: %s", buf)

	formattedRes, err := imports.Process(outFile, buf.Bytes(), nil)
	if err != nil {
		return fmt.Errorf("can't format generated file: %s", err)
	}

	var outF *os.File
	outF, err = os.OpenFile(outFile, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0640)
	if err != nil {
		return fmt.Errorf("can't open out file: %s", err)
	}
	defer func() {
		if e := outF.Close(); e != nil {
			log.Printf("can't close file: %s", e)
		}
	}()

	if _, err = outF.Write(formattedRes); err != nil {
		return fmt.Errorf("can't write to out file: %s", err)
	}

	return nil
}
